fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-style=file, -i]
        exclude: ^inc/spdlog/
      - id: clang-tidy
        args: [-p=./build/compile_commands.json]
        exclude: ^inc/spdlog/
      - id: cppcheck
        exclude: ^inc/spdlog/
